platform :ios, '6.0'
inhibit_all_warnings!

pod 'Parse'
pod 'MBProgressHUD'
pod 'UIAlertView+Blocks'
pod 'AFNetworking', '~> 1.3.3'

target :HannahLunchAdminAppTests, :exclusive => true do
    pod 'OCMock'
    pod 'OCHamcrest'
end
